version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/nginx.conf:/etc/nginx/default.conf
            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: docker/php-fpm/
        depends_on:
            - mysql
        volumes:
            - ./:/var/www/symfony
        working_dir: /var/www/symfony

    mysql:
        image: mysql:5.6
        user: "1000:50"
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - "./docker/db:/var/lib/mysql"
